version: "3"

services:
  flask_db:
    image: postgres
    restart: always
    container_name: flask_db
    environment:
      - POSTGRES_DB=flaskdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5435:5432
    volumes:
      - flask_db:/var/lib/postgresql/data
  flask:
    build: .
    container_name: flask
    entrypoint:
      - python
      - -u
      - main.py
    depends_on:
      - flask_db
    links:
      - flask_db:flask_db
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always
    environment:
      - POSTGRES_HOST=flask_db
      - POSTGRES_DB=flaskdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_PORT=5435
volumes:
  flask_db:
